-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "jobDescription" DROP NOT NULL,
ALTER COLUMN "jobPostDate" DROP NOT NULL,
ALTER COLUMN "jobAddedDate" DROP NOT NULL,
ALTER COLUMN "jobAddedDate" SET DEFAULT CURRENT_TIMESTAMP;
